### ISSUE TITLE
How to update HassOS

### ISSUE THREAD

**Issue by gerard33** [whiskerz007/proxmox_hassos_install#11]
Thanks for this excellent guide. Installing hass.io has never been so easy :+1: 

I have a question on how to update HassOS. Version 2.9 is installed and now version 2.10 is available.
When I press the update button in the Hassio - System tab I get the following errors.

```
19-02-23 22:00:48 INFO (MainThread) [hassio.hassos] Fetch OTA update from https://github.com/home-assistant/hassos/releases/download/2.10/hassos_ova-2.10.raucb
19-02-23 22:05:49 WARNING (MainThread) [hassio.hassos] Can't fetch versions from https://github.com/home-assistant/hassos/releases/download/2.10/hassos_ova-2.10.raucb: 
19-02-23 22:05:49 ERROR (MainThread) [asyncio] SSL error errno:1 reason: KRB5_S_INIT
protocol: <uvloop.loop.SSLProtocol object at 0x7fe5f93209b0>
transport: <TCPTransport closed=False reading=False 0x55a0f3759538>
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 189, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
```

And in the Host System tile (Hass.io - System tab) it shows `Error: 502: Bad Gateway` just below the hardware button.

**Comment by whiskerz007** [comment]
This seems to be a problem with Home-Assistant. Please review home-assistant/home-assistant#21270.

**Comment by gerard33** [comment]
I retried it again yesterday and this time the update was successfull and running on HassOS 2.10 now.
