### ISSUE TITLE
Monitoring disk and system resources

### ISSUE THREAD

**Issue by dasb00ter** [whiskerz007/proxmox_hassos_install#28]
I can see in some of the other issues that people can see their disk usage. I am getting an error when I tried using the system_monitor component and I thought (based on a bit of googlefu) that it might be due to the "containerized" nature of the proxmon install. How can I monitor in the front end the disk and memory usage of proxmox hassio. I see there is a way in the command line to enlarge your disk in the readme so I will review that.

**Comment by dasb00ter** [comment]
Sorry forgot to include the log:
`systemmonitor: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/systemmonitor/sensor.py", line 125, in update
    self._state = psutil.disk_usage(self.argument).percent
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 2106, in disk_usage
    return _psplatform.disk_usage(path)
  File "/usr/local/lib/python3.7/site-packages/psutil/_psposix.py", line 131, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: ''`

**Comment by whiskerz007** [comment]
Home Assistant has released a new image that supports QEMU agent. This will allow for disk, RAM, and CPU utilization in the Proxmox front end. [Link](https://github.com/whiskerz007/proxmox_hassos_install/issues/30#issuecomment-573351201)
